In [85]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [86]:
df=pd.read_csv(r"Churn_Modelling.csv")

In [87]:
df.head()


apst  CustomerId   Surname  CreditScore  Geography  Gender  Age  Tenure  \
0     1    15634602  Hargrave          619      delhi  Female   42       2   
1     2    15647311      Hill          608  bangalore  Female   41       1   
2     3    15619304      Onio          502      delhi  Female   42       8   
3     4    15701354      Boni          699      delhi  Female   39       1   
4     5    15737888  Mitchell          850  bangalore  Female   43       2   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       0.00              1          1               1        101348.88   
1   83807.86              1          0               1        112542.58   
2  159660.80              3          1               0        113931.57   
3       0.00              2          0               0         93826.63   
4  125510.82              1          1               1         79084.10   

   Exited  
0       1  
1       0  
2       1  
3       0  
4       0

In [88]:
df.shape

(10000, 14)

In [89]:
df.columns

Index(['apst', 'CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender',
       'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [90]:
df.dtypes

apst                 int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   apst             10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [92]:
df.isna().sum()

apst               0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [93]:
df.sample(3)

apst  CustomerId    Surname  CreditScore  Geography  Gender  Age  \
4497  4498    15758901  Henderson          713  bangalore  Female   47   
4670  4671    15706200     Graham          637     mumbai    Male   41   
3206  3207    15596761     Hawdon          515     mumbai    Male   60   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
4497       1       0.00              1          1               0   
4670       2  138014.40              2          1               0   
3206       9  113715.36              1          1               0   

      EstimatedSalary  Exited  
4497        107825.08       1  
4670        140298.24       0  
3206         18424.24       1

In [94]:
df = df.replace({'\?': ''}, regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\?'
<>:1: SyntaxWarning: invalid escape sequence '\?'
C:\Users\Mohammed Shoeb\AppData\Local\Temp\ipykernel_17136\2075174872.py:1: SyntaxWarning: invalid escape sequence '\?'
  df = df.replace({'\?': ''}, regex=True)


In [95]:
df.sample(5)

apst  CustomerId     Surname  CreditScore  Geography  Gender  Age  \
7108  7109    15594812    Campbell          806  bangalore  Female   37   
7787  7788    15675963    Padovano          627      delhi  Female   57   
3305  3306    15574072      Ch'ien          786      delhi  Female   62   
6354  6355    15566312       Jolly          660  bangalore  Female   42   
3191  3192    15760570  Stephenson          590      delhi    Male   32   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
7108       2  137794.18              2          0               1   
7787       9       0.00              2          1               1   
3305       8       0.00              1          1               1   
6354       5       0.00              3          1               1   
3191       5       0.00              2          1               0   

      EstimatedSalary  Exited  
7108         75232.02       0  
7787        107712.42       0  
3305        165702.64       0  
6354        189016.24       1  
3191         59249.83       0

In [96]:
df.columns

Index(['apst', 'CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender',
       'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [97]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [98]:
X

array([[619, 'delhi', 'Female', ..., 1, 1, 101348.88],
       [608, 'bangalore', 'Female', ..., 0, 1, 112542.58],
       [502, 'delhi', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'delhi', 'Female', ..., 0, 1, 42085.58],
       [772, 'mumbai', 'Male', ..., 1, 0, 92888.52],
       [792, 'delhi', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [99]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [100]:
X

array([[619, 'delhi', 'Female', ..., 1, 1, 101348.88],
       [608, 'bangalore', 'Female', ..., 0, 1, 112542.58],
       [502, 'delhi', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'delhi', 'Female', ..., 0, 1, 42085.58],
       [772, 'mumbai', 'Male', ..., 1, 0, 92888.52],
       [792, 'delhi', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [101]:
from sklearn.preprocessing import LabelEncoder

l=LabelEncoder()

X[:,2]=l.fit_transform(X[:,2])

In [102]:
X

array([[619, 'delhi', 0, ..., 1, 1, 101348.88],
       [608, 'bangalore', 0, ..., 0, 1, 112542.58],
       [502, 'delhi', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'delhi', 0, ..., 0, 1, 42085.58],
       [772, 'mumbai', 1, ..., 1, 0, 92888.52],
       [792, 'delhi', 0, ..., 1, 0, 38190.78]], dtype=object)

In [103]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder="passthrough")

In [104]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [1])])

In [105]:
X=np.array(ct.fit_transform(X))

In [106]:
X

array([[0.0, 1.0, 0.0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 0.0, ..., 0, 1, 112542.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [0.0, 1.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 0.0, 1.0, ..., 1, 0, 92888.52],
       [0.0, 1.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [107]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [108]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [109]:
X_train

array([[1.0, 0.0, 0.0, ..., 1, 0, 163830.64],
       [0.0, 0.0, 1.0, ..., 1, 1, 57098.0],
       [0.0, 1.0, 0.0, ..., 1, 0, 185630.76],
       ...,
       [0.0, 1.0, 0.0, ..., 1, 0, 181429.87],
       [1.0, 0.0, 0.0, ..., 1, 1, 148750.16],
       [0.0, 0.0, 1.0, ..., 1, 0, 118855.26]], dtype=object)

In [110]:
X_test

array([[0.0, 0.0, 1.0, ..., 1, 1, 192852.67],
       [0.0, 1.0, 0.0, ..., 1, 0, 128702.1],
       [1.0, 0.0, 0.0, ..., 1, 1, 75732.25],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 0, 141533.19],
       [0.0, 0.0, 1.0, ..., 1, 1, 11276.48],
       [0.0, 0.0, 1.0, ..., 1, 0, 192950.6]], dtype=object)

In [111]:
y_train

array([0, 0, 0, ..., 0, 0, 1])

In [112]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [113]:
from xgboost import XGBClassifier
model=XGBClassifier(n_estimator = 200, max_depth = 4, learning_rate = 0.0001,random_state=0)

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

In [114]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [115]:
comaprison=pd.DataFrame({"actual":y_test,"predicted":y_pred})

In [116]:
comaprison.sample(9)

actual  predicted
816        0          0
897        1          0
35         0          0
671        0          0
204        0          0
1150       1          0
1510       0          0
514        1          0
1731       0          0

In [117]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,y_pred)

In [118]:
cm

array([[1595,    0],
       [ 405,    0]])

In [119]:
from sklearn.metrics import accuracy_score

acc=accuracy_score(y_test,y_pred)

In [120]:
acc

0.7975

In [121]:
bias=model.score(X_train,y_train)
bias

0.796

In [122]:
var=model.score(X_test,y_test)
var

0.7975

In [123]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = model, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))

Accuracy: 79.60 %


In [126]:
from lightgbm import LGBMClassifier

model2=LGBMClassifier(n_estimators=100,max_depth=4,learning_rate=0.0001,random_state=0)
model2.fit(X_train,y_train)

y_pred2=model2.predict(X_test)

[LightGBM] [Info] Number of positive: 1632, number of negative: 6368
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000211 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 858
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 12
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.204000 -> initscore=-1.361479
[LightGBM] [Info] Start training from score -1.361479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -

In [127]:
y_pred2

array([0, 0, 0, ..., 0, 0, 0])

In [128]:
from sklearn.metrics import confusion_matrix

cm2=confusion_matrix(y_test,y_pred2)

In [129]:
cm

array([[1595,    0],
       [ 405,    0]])

In [130]:
from sklearn.metrics import accuracy_score
acc2=accuracy_score(y_test,y_pred2)
acc

0.7975

In [132]:
bias2=model2.score(X_train,y_train)
bias

0.796